# Generated by Django 4.0.3 on 2022-04-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('link', models.URLField()),
                ('image', models.CharField(blank=True, default='https://i.imgur.com/BSnwSzw.png', max_length=2000, null=True)),
                ('description', models.CharField(blank=True, max_length=350, null=True)),
                ('directions', models.CharField(blank=True, max_length=750, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=250, null=True)),
                ('tags', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
