# Generated by Django 4.0.3 on 2022-04-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0002_recipes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='description',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='directions',
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='tags',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
